apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "authentication"
  template:
    metadata:
      name: authentication
      labels:
        app: "authentication"
    spec:
      containers:
      - name: authentication
        image: authentication:v1.0.0
        ports:
          - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: "authentication"
spec:
  selector:
    app: "authentication"
  ports:
  - name: "application-port"
    port: 3000
    targetPort: 3000